### ISSUE TITLE
Feature Request: Support for Qwiic Scale

### ISSUE THREAD

**Issue by arbernat** [sparkfun/Qwiic_Py#3]
I'd like to use this for four qwiic scale devices (https://www.sparkfun.com/products/15242, chipset NAU7802). Has there been any initial effort in this area? Anything I can help with?

**Comment by Billy-Bogardus** [comment]
You will have to use An I2C multiplexer. The Data Sheet says that the Device address is permanent.
This Product (https://www.sparkfun.com/products/14685) should get you going.

**Comment by arbernat** [comment]
That's good to know - I didn't realize the devices had the same i2c address. I haven't been able to get one at a time working; they're detected as a default instead and I didn't see any mention of the chipset in the python source. I'll take a look at the arduino examples and start porting work.

**Comment by artemtk** [comment]
I am interested in the Python code for Qwiic Scale as well. Seems like Qwiic_Py has support for most of Qwiic devices except the scale one. We need to use Scale in our project in addition to the other sensors. Let me know if the work has started before I start porting myself the Arduino code to Python. Thank you.

**Comment by santaimpersonator** [comment]
One of our customers ported our Arduino library to Python and linked it for other users:

https://www.sparkfun.com/products/15242#comment-5eb077fac35147318950d323

**Comment by santaimpersonator** [comment]
**Update:** I am working on a SparkFun package in my spare time.

**Comment by santaimpersonator** [comment]
While the `README.md` still needs to be updated, my coworker has created a SparkFun Python package for the Qwiic scale:
https://github.com/sparkfun/Qwiic_NAU7802_Py
